/**
 * This is generated by https://github.com/damoebius/swagger-hx-codegen
 * Brorrowed for testing the code first swagger json generator
 */

package;

import tink.http.containers.*;
import tink.http.Response;
import tink.web.routing.*;

/**
 * This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 * @class Api
 * @param {(string)} [domainOrOptions] - The project domain.
 */
interface Api {


    /**
    * Add a new pet to the store
    * 
    **/
    @:post('/pet')
    function addPet(body:Pet):Void;

    /**
    * Update an existing pet
    * 
    **/
    @:put('/pet')
    function updatePet(body:Pet):Void;

    /**
    * Finds Pets by status
    * Multiple status values can be provided with comma separated strings
    **/
    @:get('/pet/findByStatus')
    function findPetsByStatus(query:{ status:Array<String> }):Array<Pet>;
    // function findPetsByStatus(status:Array<String>):Array<Pet>;

    /**
    * Finds Pets by tags
    * Muliple tags can be provided with comma separated strings. Use         tag1, tag2, tag3 for testing.
    **/
    @:get('/pet/findByTags')
    function findPetsByTags(query: { tags:Array<String> }):Array<Pet>;
    // function findPetsByTags(tags:Array<String>):Array<Pet>;

    /**
    * Find pet by ID
    * Returns a single pet
    **/
    @:get('/pet/$petId')
    function getPetById(petId:Int):Pet;

    /**
    * Updates a pet in the store with form data
    * 
    **/
    @:post('/pet/$petId')
    function updatePetWithForm(petId:Int,query: {name:String,status:String}):Void;
    // function updatePetWithForm(petId:Int,name:String,status:String):Void;

    /**
    * Deletes a pet
    * 
    **/
    @:delete('/pet/$petId')
    function deletePet(petId:Int, header: { api_key:String }):Void;
    // function deletePet(api_key:String,petId:Int):Void;

    /**
    * uploads an image
    * 
    **/
    @:post('/pet/$petId/uploadImage')
    function uploadFile(petId:Int,additionalMetadata:String,file:String):ApiResponse;

    /**
    * Returns pet inventories by status
    * Returns a map of status codes to quantities
    **/
    @:get('/store/inventory')
    function getInventory():Any;

    /**
    * Place an order for a pet
    * 
    **/
    @:post('/store/order')
    function placeOrder(body:Order):Order;

    /**
    * Find purchase order by ID
    * For valid response try integer IDs with value >= 1 and <= 10.         Other values will generated exceptions
    **/
    @:get('/store/order/$orderId')
    function getOrderById(orderId:Int):Order;

    /**
    * Delete purchase order by ID
    * For valid response try integer IDs with positive integer value.         Negative or non-integer values will generate API errors
    **/
    @:delete('/store/order/$orderId')
    function deleteOrder(orderId:Int):Void;

    /**
    * Create user
    * This can only be done by the logged in user.
    **/
    @:post('/user')
    function createUser(body:User):Void;

    /**
    * Creates list of users with given input array
    * 
    **/
    @:post('/user/createWithArray')
    function createUsersWithArrayInput(body:Array<User>):Void;

    /**
    * Creates list of users with given input array
    * 
    **/
    @:post('/user/createWithList')
    function createUsersWithListInput(body:Array<User>):Void;

    /**
    * Logs user into the system
    * 
    **/
    @:get('/user/login')
    function loginUser(username:String,password:String):String;

    /**
    * Logs out current logged in user session
    * 
    **/
    @:get('/user/logout')
    function logoutUser():Void;

    /**
    * Get user by user name
    * 
    **/
    @:get('/user/$username')
    function getUserByName(username:String):User;

    /**
    * Updated user
    * This can only be done by the logged in user.
    **/
    @:put('/user/$username')
    function updateUser(username:String,body:User):Void;

    /**
    * Delete user
    * This can only be done by the logged in user.
    **/
    @:delete('/user/$username')
    function deleteUser(username:String):Void;
}

typedef Order = {
    ?id:Int,
    ?petId:Int,
    ?quantity:Int,
    ?shipDate:String,
    ?status:String,
    ?complete:Bool,
}

typedef Category = {
    ?id:Int,
    ?name:String,
}

typedef User = {
    ?id:Int,
    ?username:String,
    ?firstName:String,
    ?lastName:String,
    ?email:String,
    ?password:String,
    ?phone:String,
    ?userStatus:Int,
}

typedef Tag = {
    ?id:Int,
    ?name:String,
}

typedef Pet = {
    ?id:Int,
    ?category:Category,
    name:String,
    photoUrls:Array<String>,
    ?tags:Array<Tag>,
    ?status:String,
}

typedef ApiResponse = {
    ?code:Int,
    ?type:String,
    ?message:String,
}

